Bootstrap repository
rust-at-night/rust-at-night-website pull request #6
Opened 2023-07-18 16:41 UTC by alisomay

# Patience
There will be a long PR description here in the next hours. Please don't start reviewing before that 🙏

2023-07-18 20:02 UTC, berkantsoytas requested changes

2023-07-18 20:02 UTC, berkantsoytas commented on website-backend/src/data.rs
I think using the term "model" instead of "data" is more appropriate for data models. Can you change the name of the file?

2023-07-18 20:02 UTC, berkantsoytas commented on website-backend/src/data/post.rs
I think using the term "model" instead of "data" is more appropriate for data models. Can you change the name of the folder?

2023-07-18 20:11 UTC, alisomay commented on website-backend/src/main.rs
It depends on the environment. 
So the `options.rs` uses `clap` to parse the env vars.
If they're not exported in the environment then uses the default values.
In this case the default values act as the local environment and do not need to be specified and parsed from a `.env` file which I thinkis more convenient.

In a remote environment though the environment variables will be set by the remote environment in a proper way.
So it overrides the default values if necessary.

I can see what might confuse you.

For example: 

```rust
pub struct Options {
    /// Socket address to listen on
    #[clap(short, long, env = "ADDR", default_value = "0.0.0.0:8081")]
    pub addr: SocketAddr,

    /// Url of this service.
    #[clap(long, env = "ROOT_URL", default_value = "http://localhost:8081")]
    pub root_url: Url,
    
    //... and others
}
```
is parsed from `ADDR`, `ROOT_URL` etc. you get the idea.

2023-07-18 20:14 UTC, alisomay commented on website-backend/src/data.rs
You may be right but also the structs in `data.rs` module might contain methods or trait implementations also. 
Just give it a second thought since data is a more general name than `model` and might give us more freedom in the module.

On the other hand it does not matter very much for me. 
If you still think that it is better that the module is named as `model` please put a thumbs up emoji under this comment.

I'll gladly change it.

2023-07-18 20:15 UTC, alisomay commented on README.md
> +To be written..
What do you mean here? 😅

2023-07-18 20:18 UTC, alisomay commented on website-backend/src/main.rs
If you'd like to override them locally. You can as well export them to your shell. 
If they're changed that frequently in local environments we can either change the defaults or I can easily include `dotenv` as a dependency so `.env` files are parsed. 

But I'd say let's wait for the need.

2023-07-19 07:27 UTC, dvtkrlbs commented on .gitignore
Maybe we can expand this with common configurations. For example .DS_Store and some common editor artifacts.

2023-07-19 07:43 UTC, ozankasikci commented
Awesome work, I'm in awe.

Tech stack, initial CI integration, Project structure are all looking great as ground work.

When it comes to the FE, we need to discuss if we're going to use server-side rendering or go with a SPA.

2023-07-19 07:44 UTC, ozankasikci approved these changes

2023-07-19 08:12 UTC, alisomay commented on .gitignore
I think it is a good idea! I'll amend the last commit.

2023-07-19 08:14 UTC, alisomay commented
> Awesome work, I'm in awe.
> 
> Tech stack, initial CI integration, Project structure are all looking great as ground work.
> 
> When it comes to the FE, we need to discuss if we're going to use server-side rendering or go with a SPA. Still there is nothing wrong with keeping the PR as is for now, imho.
> 
> LGTM!

Definitely agreed. We also need a sort of component owner for the frontend. Maybe Orhan will do it or @dvtkrlbs.
The boilerplate I've shared is just to have something working. Frontend part is not a suggestion.

2023-07-19 09:41 UTC, berkantsoytas approved these changes

2023-07-19 11:02 UTC, berkantsoytas approved these changes

2023-07-19 12:08 UTC, merged

2023-07-19 12:13 UTC, te-ori commented
> > Awesome work, I'm in awe.
> > Tech stack, initial CI integration, Project structure are all looking great as ground work.
> > When it comes to the FE, we need to discuss if we're going to use server-side rendering or go with a SPA. Still there is nothing wrong with keeping the PR as is for now, imho.
> > LGTM!
> 
> Definitely agreed. We also need a sort of component owner for the frontend. Maybe Orhan will do it or @dvtkrlbs. The boilerplate I've shared is just to have something working. Frontend part is not a suggestion.

I have developed few spa with vuejs, but not experienced server side rendering. So, it seems more sensible to start as spa and then to do experiments with ssr. But if there are someone who guide us to use ssr, it can be first choise.